### ISSUE TITLE
Data not update in graphs

### ISSUE THREAD

**Issue by felixloeser** [ospin-web-dev/non-repo-issues#112]
### Description

During a call with Heidolph, the data in the graphs was not updated. it required a full page refresh to show new data, but that also only showed data at the time of refresh. at no point was the data continuously updated
When creating a new process on the same device, the data was shown continuously updating in the graphs

### How severe is the impact for you

major

### Has this been encountered internally or by a customer

internal, external

### URL link to the view with the problem

https://ospin-app.com/device/01d8eb46-04fe-4369-a165-24eab5411dca/process/fb7bb5d8-a758-41b2-9d92-4b7ed15b1a6a?active-tab=dataviewer

### Steps To Reproduce

don't know

### In wich environments did you encounter the bug?

Production

**Comment by FelixMZ2018** [comment]
Pusher reported degraded service for this exact time period, we cloned the process and were able to subscribe to it without any problem, checked cloudwatch for subscriptions endpoints as well as the pusher debug console and there were no reported errors 

unless we can rerproduce it this is most likely due to pusher degraded service ... the curse of us-east-1 strikes again
